# Generated by Django 4.1.2 on 2022-10-30 00:36

import app.validators
import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Search Point Longitude')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Search Point Latitude')),
                ('radius', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Search Point Radius')),
                ('colour', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None, verbose_name='Username Colour')),
                ('rank', models.CharField(choices=[('DI', 'Diamond'), ('GO', 'Gold'), ('SI', 'Silver'), ('BR', 'Bronze'), ('UR', 'Unranked')], default='UR', max_length=2, verbose_name='Rank')),
                ('emoji', models.CharField(blank=True, max_length=7, null=True, validators=[app.validators.validate_emoji], verbose_name='Custom Emoji')),
                ('BaseUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'verbose_name': 'Fly Tipping Report',
            },
        ),
    ]
