# Generated by Django 4.1.2 on 2022-10-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_baseuser_user__base_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Duck Points'),
        ),
    ]
