# Generated by Django 4.1.2 on 2022-10-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_profile_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Duck Points'),
        ),
    ]
