# Generated by Django 4.1.2 on 2022-10-30 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_added_to_wall',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last time added to wall'),
        ),
    ]
