# Generated by Django 4.1.2 on 2022-10-30 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile__added_to_wall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='_added_to_wall',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 4, 52, 59, 863203, tzinfo=datetime.timezone.utc), verbose_name='Last time added to wall'),
        ),
    ]
