# Generated by Django 4.1.2 on 2022-10-30 08:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile__added_to_wall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='_added_to_wall',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 7, 30, 53, 98766, tzinfo=datetime.timezone.utc), verbose_name='Last time added to wall'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='radius',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Search Point Radius'),
        ),
    ]
