# Generated by Django 4.1.2 on 2022-10-30 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_profile__added_to_wall_alter_profile_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='_added_to_wall',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 7, 45, 58, 232377, tzinfo=datetime.timezone.utc), verbose_name='Last time added to wall'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Search Point Latitude'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Search Point Longitude'),
        ),
    ]
