# Generated by Django 4.1.2 on 2022-10-30 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_profile__added_to_wall_alter_profile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='_added_to_wall',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 7, 47, 12, 431340, tzinfo=datetime.timezone.utc), verbose_name='Last time added to wall'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=19, verbose_name='Search Point Latitude'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=19, verbose_name='Search Point Longitude'),
        ),
    ]
